In [ ]:
#  GMM for Each Image based on Average of Components

In [37]:
path= ('/home/roopesh/PycharmProjects/test_ready_iris_classification/Ready_Iris_Classification/Result/Multiple_CSV/*.csv')  # RGB Pixel Path for Multiple CSV in Folder   
print('GMM Running!!!.....')
for idx,csv_file in enumerate(glob.glob(path) ):
    input_csv_pixels= pd.read_csv(csv_file)
    
# GMM model

    gm=GaussianMixture(covariance_type='spherical', init_params='kmeans', max_iter=250,
            means_init=None, n_components=6, n_init=10, precisions_init=None,
            random_state=60, reg_covar=1e-06, tol=0.001, verbose=0,
            verbose_interval=10, warm_start=False, weights_init=None).fit(input_csv_pixels)

# Soft Clustering

    # cluster= gm.predict(input_csv_pixels)

# Evaluate the components’ density for each sample.(evaluate the probability of each sample belonging to each component) hard clustering)
    cluster_probability= gm.predict_proba(input_csv_pixels)
    cluster1 = pd.DataFrame(cluster_probability)
    cluster2 = cluster1
    df= pd.DataFrame(cluster2.mean(axis=0))
    df=df.T
#     df.to_csv(f'/home/roopesh/Desktop/GMM_Multiple_CSV/{idx}.csv', sep=',', index=False, header=False) # Enter Your Path To be saved:
    pred2 = pd.Series([idx for x in range(len(df.index))]) # CREATE A SERIES OF IDX
    prediction1=pd.concat([df, pred2],axis=1)
    c=('Prob_1stComp','Prob_2ndComp','Prob_3rdComp','Prob_4thComp','Prob_5thComp','Prob_6thComp','Idx_csv')
    prediction1.to_csv(f'/home/roopesh/Desktop/GMM_Multiple_CSV/{idx}.csv', sep=',', index=False, header=c) # Enter Your Path To be saved:
   
    
# Combining Multiple Csv in to one CSV of all samples

    os.chdir("/home/roopesh/Desktop/GMM_Multiple_CSV") # Enter Your Path For Specific Directory of prediction1.to_csv
    extension = 'csv'
    all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
    combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])

# Merging Labelled hand annotated Iris Color CSV with Combined CSV

    df=pd.read_csv('/home/roopesh/Desktop/Iris_Label_830.csv')  # Enter Your Path : Hand Annotated iris color.csv
    df1=combined_csv
    df = df.rename(columns={'CSV_File_No': 'Idx_csv'})
    final = df.merge(df1, how='left')
    final.to_csv("/home/roopesh/Desktop/Input_for_classifier/GmmProb_Label_Iris.csv", index=False, encoding='utf-8-sig')

print('GMM is Ready, Output Loaded to Classifier !!!.....')

print('Fininsh all')

# Plotting GMM
    # plot_3d_gmm_2d(gm) # Loads from the Luxvis.py Module

#  write Each CSV for each sample of GMM cluster_probability



GMM Running!!!.....
GMM is Ready, Output Loaded to Classifier !!!.....
Fininsh all


In [29]:
df=pd.read_csv('/home/roopesh/Desktop/Iris_Label_830.csv')  
df

CSV_File_No Iris_Color
0              0       Blue
1              1      Black
2              2      Black
3              3       Grey
4              4      Hazel
..           ...        ...
782          778      Hazel
783          779      Hazel
784          780      Hazel
785          779      Hazel
786          780      Hazel

[787 rows x 2 columns]

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
from sklearn.metrics import roc_auc_score,roc_curve,auc
import warnings
warnings.filterwarnings("ignore")


def classification (X_train,X_test,y_train,y_test):

    from sklearn.linear_model import LogisticRegression
    logreg = LogisticRegression(solver='saga', dual=False, tol=0.0001,fit_intercept=1, C=100.0, penalty='elasticnet',max_iter=800, l1_ratio=0, random_state=60)
    logreg.fit(X_train,y_train)
    y_pred = logreg.predict(X_test)
    print('logistic_regression_classification_report',classification_report(y_test,y_pred))
    print('logistic_regression_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('logistic_regression_accuracy_score',accuracy_score(y_test,y_pred))
    print('logistic_regression_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=250, max_depth=15, min_samples_split=10, min_samples_leaf=5).fit(X_train,y_train)
    y_pred = rf.predict(X_test)
    print('random_forest_classification_report',classification_report(y_test,y_pred))
    print('random_forest_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('random_forest_accuracy_score',(accuracy_score(y_test,y_pred)))
    print('random_forest_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.svm import SVC
    svm = SVC(kernel='rbf',C=1,gamma=0.1)
    svm.fit(X_train,y_train)
    y_pred = svm.predict(X_test)
    print('svm_classification_report',classification_report(y_test,y_pred))
    print('svm_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('svm_accuracy_score',accuracy_score(y_test,y_pred))
    print('svm_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    print('knn_classification_report',classification_report(y_test,y_pred))
    print('knn_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('knn_accuracy_score',accuracy_score(y_test,y_pred))
    print('knn_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,y_train)
    y_pred = gnb.predict(X_test)
    print('gaussian_naive_bayes_classification_report',classification_report(y_test,y_pred))
    print('gaussian_naive_bayes_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('gaussian_naive_bayes_accuracy_score',accuracy_score(y_test,y_pred))
    print('gaussian_naive_bayes_f1_score',f1_score(y_test,y_pred, average='micro'))
    return y_pred

if __name__ == "__main__":
    print()

    data=pd.read_csv("/home/roopesh/Desktop/Input_for_classifier/GmmProb_Label_Iris.csv", sep=',')
    data1=data.dropna(inplace=True)
    from sklearn import preprocessing
 
    x= data[['Prob_1stComp', 'Prob_2ndComp', 'Prob_3rdComp','Prob_4thComp','Prob_5thComp','Prob_6thComp']]
    y=data[['Iris_Color']]
    x1_train, x1_test, y1_train, y1_test = train_test_split(x,y,test_size=0.20, shuffle= True)
    # Normalizing the dataset
    
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    scaler.fit(x1_train)
    scaler.fit(x1_test)
    x1_train = scaler.transform(x1_train)
    x1_test = scaler.transform(x1_test)

    classification( x1_train,x1_test,y1_train,y1_test)


logistic_regression_classification_report               precision    recall  f1-score   support

       Black       0.16      0.22      0.18        27
        Blue       0.20      0.12      0.15        26
       Brown       0.33      0.15      0.21        33
       Green       0.11      0.22      0.14        23
        Grey       0.10      0.18      0.13        22
       Hazel       0.00      0.00      0.00        22

    accuracy                           0.15       153
   macro avg       0.15      0.15      0.14       153
weighted avg       0.16      0.15      0.14       153

logistic_regression_confusion_matrix [[ 6  4  1 10  6  0]
 [ 2  3  4 10  7  0]
 [ 7  3  5  8 10  0]
 [ 7  3  1  5  7  0]
 [ 8  2  1  7  4  0]
 [ 8  0  3  6  5  0]]
logistic_regression_accuracy_score 0.1503267973856209
logistic_regression_f1_score 0.1503267973856209
random_forest_classification_report               precision    recall  f1-score   support

       Black       0.13      0.15      0.14        27
   

In [88]:
#  GMM for each image based on Gmm means:


In [95]:
import os

def mediapipe_csv_gmm_csv(path):
    
    files = os.listdir(files_dir)
    sorted_csv = sorted(files, key=lambda x:int(x[9:-4])) # Sorting the images in ascending order based on the number in the name of the image
    
    for idx, csv_file in enumerate(sorted_csv):
        if csv_file.lower().endswith('.csv'):
            mediapipe_csv_path = files_dir + '/' + csv_file
            input_csv_pixels= pd.read_csv(mediapipe_csv_path)
            
            print(csv_file)

# GMM model

            gm=GaussianMixture(covariance_type='spherical', init_params='kmeans', max_iter=2500,
                    means_init=None, n_components=5, n_init=10, precisions_init=None,
                    random_state=60, reg_covar=1e-06, tol=0.001, verbose=0,
                    verbose_interval=10, warm_start=False, weights_init=None).fit(input_csv_pixels)

            cluster3 = pd.DataFrame(gm.means_)

# flatten from 3d to 1 d (gm.means_)

            cluster3 = cluster3.to_numpy().flatten()
            df= pd.DataFrame(cluster3)
            df=df.T
       
 # Soft Clustering

            # cluster= gm.predict(input_csv_pixels)

# Evaluate the components’ density for each sample.(evaluate the probability of each sample belonging to each component) hard clustering)
            
            #     cluster_probability= gm.predict_proba(input_csv_pixels)
            #     cluster1 = pd.DataFrame(cluster_probability)
            #     cluster2 = cluster1
            #     df= pd.DataFrame(cluster2.mean(axis=0))
            #     df=df.T

# df.to_csv(f'/home/roopesh/Desktop/GMM_Multiple_CSV/{idx}.csv', sep=',', index=False, header=False) # Enter Your Path To be saved:
            
            pred2 = pd.Series([idx for x in range(len(df.index))]) # CREATE A SERIES OF IDX
            prediction1=pd.concat([df, pred2],axis=1)
            c=('GMeans_H1_Comp','GMeans_L1_Comp','GMeans_S1_Comp',
               'GMeans_H2_Comp','GMeans_L2_Comp','GMeans_S2_Comp','GMeans_H3_Comp',
               'GMeans_L3_Comp','GMeans_S3_Comp',
               'GMeans_H4_Comp','GMeans_L4_Comp','GMeans_S4_Comp', 
               'GMeans_H5_Comp','GMeans_L5_Comp','GMeans_S5_Comp','Idx_csv')         
            prediction1.to_csv(f'/home/roopesh/Desktop/HSL/GMM_csv_out/Gmm_{idx}.csv', sep=',', index=False, header=c) # Enter Your Path To be saved:


# Combining Multiple Csv in to one CSV of all samples

            os.chdir("/home/roopesh/Desktop/HSL/GMM_csv_out") # Enter Your Path For Specific Directory of prediction1.to_csv
            extension = 'csv'
            all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
            combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames])

# Merging Labelled hand annotated Iris Color CSV with Combined CSV

            df=pd.read_csv('/home/roopesh/Desktop/HSL/Iris_Label_830.csv')  # Enter Your Path : Hand Annotated iris color.csv
            df1=combined_csv
            df = df.rename(columns={'CSV_File_No': 'Idx_csv'})
            final = df.merge(df1, how='left')
            final.to_csv("/home/roopesh/Desktop/HSL/Input_csv_Classifier/GmmProb_Label_Iris.csv", index=False, encoding='utf-8-sig')
        
    print('GMM is Ready, Output Loaded to Classifier !!!.....')
    print('Fininsh all')

        # Plotting GMM
            # plot_3d_gmm_2d(gm) # Loads from the Luxvis.py Module

        #  write Each CSV for each sample of GMM cluster_probability

if __name__=='__main__':
    files_dir =  '/home/roopesh/Desktop/HSL/Mediapipe_csv_out/'
    mediapipe_csv_gmm_csv(files_dir)




CSV-image0.csv
CSV-image1.csv
CSV-image2.csv
CSV-image3.csv
CSV-image4.csv
CSV-image5.csv
CSV-image6.csv
CSV-image7.csv
CSV-image8.csv
CSV-image9.csv
CSV-image10.csv
CSV-image11.csv
CSV-image12.csv
CSV-image13.csv
CSV-image14.csv
CSV-image15.csv
CSV-image16.csv
CSV-image17.csv
CSV-image18.csv
CSV-image19.csv
CSV-image20.csv
CSV-image21.csv
CSV-image22.csv
CSV-image23.csv
CSV-image24.csv
CSV-image25.csv
CSV-image26.csv
CSV-image27.csv
CSV-image28.csv
CSV-image29.csv
CSV-image30.csv
CSV-image31.csv
CSV-image32.csv
CSV-image33.csv
CSV-image34.csv
CSV-image35.csv
CSV-image36.csv
CSV-image37.csv
CSV-image38.csv
CSV-image39.csv
CSV-image40.csv
CSV-image41.csv
CSV-image42.csv
CSV-image43.csv
CSV-image44.csv
CSV-image45.csv
CSV-image46.csv
CSV-image47.csv
CSV-image48.csv
CSV-image49.csv
CSV-image50.csv
CSV-image51.csv
CSV-image52.csv
CSV-image53.csv
CSV-image54.csv
CSV-image55.csv
CSV-image56.csv
CSV-image57.csv
CSV-image58.csv
CSV-image59.csv
CSV-image60.csv
CSV-image61.csv
CSV-image62.csv
CS

CSV-image499.csv
CSV-image500.csv
CSV-image501.csv
CSV-image502.csv
CSV-image503.csv
CSV-image504.csv
CSV-image505.csv
CSV-image506.csv
CSV-image507.csv
CSV-image508.csv
CSV-image509.csv
CSV-image510.csv
CSV-image511.csv
CSV-image512.csv
CSV-image513.csv
CSV-image514.csv
CSV-image516.csv
CSV-image517.csv
CSV-image518.csv
CSV-image519.csv
CSV-image520.csv
CSV-image521.csv
CSV-image522.csv
CSV-image523.csv
CSV-image524.csv
CSV-image526.csv
CSV-image527.csv
CSV-image528.csv
CSV-image529.csv
CSV-image530.csv
CSV-image531.csv
CSV-image532.csv
CSV-image533.csv
CSV-image535.csv
CSV-image536.csv
CSV-image537.csv
CSV-image538.csv
CSV-image539.csv
CSV-image541.csv
CSV-image542.csv
CSV-image543.csv
CSV-image544.csv
CSV-image547.csv
CSV-image548.csv
CSV-image549.csv
CSV-image550.csv
CSV-image551.csv
CSV-image552.csv
CSV-image553.csv
CSV-image554.csv
CSV-image555.csv
CSV-image556.csv
CSV-image557.csv
CSV-image558.csv
CSV-image559.csv
CSV-image560.csv
CSV-image561.csv
CSV-image562.csv
CSV-image563.c

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
from sklearn.metrics import roc_auc_score,roc_curve,auc
import warnings
warnings.filterwarnings("ignore")


def classification (X_train,X_test,y_train,y_test):

    from sklearn.linear_model import LogisticRegression
    logreg = LogisticRegression(solver='saga', dual=False, tol=0.0001,fit_intercept=1, C=100.0, penalty='elasticnet',max_iter=800, l1_ratio=0, random_state=60)
    logreg.fit(X_train,y_train)
    y_pred = logreg.predict(X_test)
    print('logistic_regression_classification_report',classification_report(y_test,y_pred))
    print('logistic_regression_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('logistic_regression_accuracy_score',accuracy_score(y_test,y_pred))
    print('logistic_regression_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=250, max_depth=15, min_samples_split=10, min_samples_leaf=5).fit(X_train,y_train)
    y_pred = rf.predict(X_test)
    print('random_forest_classification_report',classification_report(y_test,y_pred))
    print('random_forest_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('random_forest_accuracy_score',(accuracy_score(y_test,y_pred)))
    print('random_forest_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.svm import SVC
    svm = SVC(kernel='rbf',C=1,gamma=0.1)
    svm.fit(X_train,y_train)
    y_pred = svm.predict(X_test)
    print('svm_classification_report',classification_report(y_test,y_pred))
    print('svm_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('svm_accuracy_score',accuracy_score(y_test,y_pred))
    print('svm_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    print('knn_classification_report',classification_report(y_test,y_pred))
    print('knn_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('knn_accuracy_score',accuracy_score(y_test,y_pred))
    print('knn_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,y_train)
    y_pred = gnb.predict(X_test)
    print('gaussian_naive_bayes_classification_report',classification_report(y_test,y_pred))
    print('gaussian_naive_bayes_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('gaussian_naive_bayes_accuracy_score',accuracy_score(y_test,y_pred))
    print('gaussian_naive_bayes_f1_score',f1_score(y_test,y_pred, average='micro'))
    return y_pred

if __name__ == "__main__":
    print()

    data=pd.read_csv("/home/roopesh/Desktop/HSL/Input_csv_Classifier/GmmProb_Label_Iris.csv", sep=',')
    data1=data.dropna(inplace=True)
    from sklearn import preprocessing
 
    x= data[['GMeans_H1_Comp','GMeans_L1_Comp','GMeans_S1_Comp',
               'GMeans_H2_Comp','GMeans_L2_Comp','GMeans_S2_Comp','GMeans_H3_Comp',
               'GMeans_L3_Comp','GMeans_S3_Comp',
               'GMeans_H4_Comp','GMeans_L4_Comp','GMeans_S4_Comp', 
               'GMeans_H5_Comp','GMeans_L5_Comp','GMeans_S5_Comp']]
    y=data[['Iris_Color']]
    x1_train, x1_test, y1_train, y1_test = train_test_split(x,y,test_size=0.20, shuffle=True)
    # Normalizing the dataset
    
    from sklearn.preprocessing import StandardScaler
    
#     scaler = MinMaxScaler()

    scaler = StandardScaler()
    scaler.fit(x1_train)
    scaler.fit(x1_test)
    x1_train = scaler.transform(x1_train)
    x1_test = scaler.transform(x1_test)

    classification( x1_train,x1_test,y1_train,y1_test)


logistic_regression_classification_report               precision    recall  f1-score   support

       Black       0.33      0.35      0.34        31
        Blue       0.16      0.15      0.16        26
       Brown       0.19      0.27      0.22        26
       Green       0.12      0.20      0.15        20
        Grey       0.23      0.11      0.15        28
       Hazel       0.10      0.05      0.06        21

    accuracy                           0.20       152
   macro avg       0.19      0.19      0.18       152
weighted avg       0.20      0.20      0.19       152

logistic_regression_confusion_matrix [[11  4  8  4  2  2]
 [ 3  4  7  9  2  1]
 [ 6  5  7  3  3  2]
 [ 5  3  3  4  2  3]
 [ 8  6  7  3  3  1]
 [ 0  3  5 11  1  1]]
logistic_regression_accuracy_score 0.19736842105263158
logistic_regression_f1_score 0.19736842105263158
random_forest_classification_report               precision    recall  f1-score   support

       Black       0.27      0.19      0.23        31
 